name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
    - run: npm install --no-package-lock
    - run: npm test
    - uses: coactions/setup-xvfb@v1
      with:
        run: npm run test-ui
